services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: software_crm_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - software_crm

  web:
    image: nginx:alpine
    container_name: web_server
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - "8080:80"
    networks:
      - software_crm
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: software_crm_db
    restart: unless-stopped
    tty: true
    volumes:
      - software_crm_db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - software_crm
    environment:
      MYSQL_DATABASE: software_crm
      MYSQL_ROOT_PASSWORD: 24559444
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

networks:
  software_crm:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  software_crm_db_volume:
