name: "ismael"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - my-volume:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: web_server
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - my-volume:/var/www
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 24559444
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

networks:
  laravel:

volumes:
  my-volume:
